### ISSUE TITLE
torch.rand()

### ISSUE THREAD

**Issue by dilshod-obidov** [elee02/Medical_Imaging_With_Deep_Learning#3]
### Code:
```py
import torch
torch.manual_seed(0)
print(torch.rand()) # Run twice to see the same random numbers
```
*(line 4)*  
as error suggests, rand() requires at least one argument

### Error message:
Traceback (most recent call last):
  File "Medical_Imaging_With_Deep_Learning\eli_experiments\experiment_1.py", line 4, 
in <module>
    print(torch.rand()) # Run twice to see the same random numbers
          ^^^^^^^^^^^^
TypeError: rand() received an invalid combination of arguments - got (), but expected one of:
  (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout 
layout, torch.device device, bool pin_memory, bool requires_grad)
  (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
  (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
  (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by elee02** [comment]
Problematic Code:
print(torch.rand()) # Run twice to see the same random numbers

Fixed Code:
print(torch.rand(1)) # Run twice to see the same random numbers

Thanks for the issue!
